
class Objects:
    EMPTY = "empty"
    PLAYER = "player"
    TILE1 = "tile1"
    TILE2 = "tile2"
    TILE3 = "tile3"
    CRATE = "crate"
    WALL = "wall"
    FAKE_WALL = "fake wall"
    BLOCK1 = "block1"
    BLOCK2 = "block2"
    TRAP = "trap"
    TRAP_DISABLE = "trap disable"
    KEY = "key"
    BOSS_KEY = "boss key"
    PLAYER = "player"
    TREASURE = "treasure"
    TREASURE_CHEST = "treasure chest"
    DOOR = "door"
    DOOR_OPEN = "door open"
    TELEPORT = "teleport"
    HOLE = "hole"
    EXIT_NEXT = "exit_next"
    EXIT_PREVIOUS = "exit_previous"
    SWITCH_1 = "switch 1"
    SWITCH_2 = "switch 2"
    SWITCH_TILE1 = "switch tile 1"
    SWITCH_TILE2 = "switch tile 2"
    LIQUID1 = "liquid1"
    LIQUID2 = "liquid2"

