
class Objects:
    PLAYER = "player"
    TILE1 = "tile1"
    TILE2 = "tile2"
    TILE3 = "tile3"
    CRATE = "crate"
    WALL = "wall"
    FAKE_WALL = "fake wall"
    BLOCK1 = "block1"
    BLOCK2 = "block2"
    TRAP = "trap"
    KEY = "key"
    BOSS_KEY = "boss key"
    PLAYER = "player"
    TREASURE = "treasure"
    TREASURE_CHEST = "treasure chest"
    DOOR = "door"
    TELEPORT = "teleport"
    HOLE = "hole"
    EXIT_NEXT = "exit_next"
    EXIT_PREVIOUS = "exit_previous"
    SWITCH_OFF = "swicth off"
    SWITCH_ON = "switch on"
    SWITCH_TILE = "switch tile"
    LIQUID1 = "liquid1"
    LIQUID2 = "liquid2"

