
class Objects:
    PLAYER = "player"
    TILE1 = "tile1"
    TILE2 = "tile2"
    TILE3 = "tile3"
    CRATE = "crate"
    WALL = "wall"
    TRAP = "trap"
    KEY = "key"
    BOSS_KEY = "boss key"
    PLAYER = "player"
    TREASURE = "treasure"
    TREASURE_CHEST = "treasure chest"
    DOOR = "door"
    TELEPORT = "teleport"
    HOLE = "hole"
    EXIT_NEXT = "exit_next"
    EXIT_PREVIOUS = "exit_previous"
